### PR TITLE
Admin notice improvements.

### PR DESCRIPTION
**Pull request by oleksandr-mykhailenko**
Small code cleanup

### CODE REVIEW

**Comment by midweste** [comment]
https://github.com/mailgun/wordpress-plugin/pull/174/files#diff-35327cdcf196c01a80be6f8a02b58f139b1e12c01bdad9aa86a4b1a3c63484f7R340

Missing check if session exists is causing warning

Warning: Undefined global variable $_SESSION in /app/web/wp-content/plugins/mailgun/includes/admin.php on line 340 Warning: Trying to access array offset on value of type null in /app/web/wp-content/plugins/mailgun/includes/admin.php on line 340

**Comment by oleksandr-mykhailenko** [comment]
> https://github.com/mailgun/wordpress-plugin/pull/174/files#diff-35327cdcf196c01a80be6f8a02b58f139b1e12c01bdad9aa86a4b1a3c63484f7R340
> 
> Missing check if session exists is causing warning
> 
> Warning: Undefined global variable $_SESSION in /app/web/wp-content/plugins/mailgun/includes/admin.php on line 340 Warning: Trying to access array offset on value of type null in /app/web/wp-content/plugins/mailgun/includes/admin.php on line 340

Gotcha, thank you for that

**Comment by midweste** [comment]
> > https://github.com/mailgun/wordpress-plugin/pull/174/files#diff-35327cdcf196c01a80be6f8a02b58f139b1e12c01bdad9aa86a4b1a3c63484f7R340
> > Missing check if session exists is causing warning
> > Warning: Undefined global variable $_SESSION in /app/web/wp-content/plugins/mailgun/includes/admin.php on line 340 Warning: Trying to access array offset on value of type null in /app/web/wp-content/plugins/mailgun/includes/admin.php on line 340
> 
> Gotcha, thank you for that

thank you! I'm sorry I don't have the time at the moment to put in a pull request.

**Comment by midweste** [comment]
Just got the most recent version, thank you so much for adding the check.  Appreciate it!

**Pull request merged**
